# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: People
    identifier: people
    weight: 20
  - name: Spin Group
    parent: people
    url: people
    weight: 10
  - name: Collaborators
    parent: people
    url: people/collaborators
    weight: 20
  - name: Former Folks
    parent: people
    url: people/past
    weight: 30
#  - name: News
#    url: post
#    weight: 30
  - name: Research
    url: research
    weight: 40
  - name: Publications
    url: publication
    weight: 50
  - name: Contact PI
    url: contact
    weight: 60
